artifacts:
  files:
  - transformed.yaml
  type: zip
phases:
  install:
    commands:
    - sudo pip install --upgrade awscli
    - aws --version
    - sudo pip install 'chalice>=1.27.0,<1.28.0'
    - sudo pip install -r requirements.txt
    - chalice package /tmp/packaged --stage prod
    - aws cloudformation package --template-file /tmp/packaged/sam.json --s3-bucket
      ${APP_S3_BUCKET} --output-template-file transformed.yaml
version: '0.1'
